import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const agents = ['alpha', 'bravo', 'charlie'].map(id => ({ id, name: id, cwd: '/workspace', backend: 'codex', model: 'test', status: 'complete', updatedAt: Date.now()/1000 }));
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  const writes = [];
  page.on('request', request => { if (request.method() !== 'GET') writes.push(request.url()); });
  await page.route('**/api/state', r => r.fulfill({ json: { mode: 'ask', agents, archived: [], messages: {}, tasks: [], taskNotes: [], inbox: [], paneLinks: {}, tags: {}, boards: [], sources: [], models: [], backends: [] } }));
  await page.route('**/api/events', r => r.fulfill({ contentType: 'text/event-stream', body: ': test\n\n' }));
  await page.route('**/api/agents/*', r => {
    const agent = agents.find(agent => r.request().url().endsWith('/' + agent.id));
    return r.fulfill({ json: { agent, timeline: [], delivery: 'start' } });
  });
  await page.goto(`${process.env.TEST_URL ?? 'http://localhost:3941'}/?agent=alpha`);
  const pane = id => page.locator(`[data-agent-pane="${id}"]`);
  await pane('alpha').waitFor();
  const picker = page.getByLabel('Choose visible agents');
  assert.equal(await picker.innerText(), '', 'Pane picker is icon-only');
  const pickerBox = await picker.boundingBox(), settingsBox = await page.getByRole('button', { name: 'Settings', exact: true }).boundingBox();
  assert.ok(Math.abs(pickerBox.x - settingsBox.x - settingsBox.width) < 2, 'Pane picker sits beside the left toolbar icons');
  assert.equal(pickerBox.width, settingsBox.width, 'Pane picker matches toolbar cell size');
  await pane('alpha').locator('[data-composer]').fill('Keep this draft.');
  await page.getByLabel('Choose visible agents').click();
  await page.getByRole('checkbox', { name: 'bravo', exact: true }).check();
  await page.getByRole('checkbox', { name: 'charlie', exact: true }).check();
  await page.getByLabel('Choose visible agents').click();
  await pane('charlie').waitFor();
  const drag = async (source, target, edge) => {
    const box = await pane(target).boundingBox();
    const handle = page.getByRole('button', { name: `Move pane ${source}`, exact: true });
    const x = edge === 'left' ? 10 : edge === 'right' ? box.width - 10 : box.width/2;
    const y = edge === 'top' ? 10 : edge === 'bottom' ? box.height - 10 : box.height/2;
    await handle.dragTo(pane(target), { targetPosition: { x, y } });
  };
  await drag('charlie', 'alpha', 'bottom');
  let a = await pane('alpha').boundingBox(), c = await pane('charlie').boundingBox(), b = await pane('bravo').boundingBox();
  assert.ok(c.y > a.y && Math.abs(c.x - a.x) < 2 && b.x > a.x, 'Nested vertical and horizontal panes share the view');
  assert.equal(await pane('alpha').locator('[data-composer]').inputValue(), 'Keep this draft.', 'Moving panes retains message drafts');
  const verticalSplit = page.locator('[role="separator"][aria-orientation="horizontal"]');
  await verticalSplit.focus();
  const before = (await pane('alpha').boundingBox()).height;
  await verticalSplit.press('ArrowDown');
  assert.ok((await pane('alpha').boundingBox()).height > before, 'Split divider resizes vertically');
  assert.ok(await page.getByRole('separator', { name: 'resize chat panes' }).count() >= 2);
  const sideDivider = page.locator('[role="separator"][aria-orientation="vertical"]').first();
  const sideBox = await sideDivider.boundingBox(), oldWidth = (await pane('alpha').boundingBox()).width;
  await page.mouse.move(sideBox.x + sideBox.width/2, sideBox.y + sideBox.height/2);
  await page.mouse.down();
  await page.mouse.move(sideBox.x + 60, sideBox.y + sideBox.height/2, { steps: 6 });
  await page.mouse.up();
  assert.ok((await pane('alpha').boundingBox()).width > oldWidth, 'Pointer dragging resizes horizontal splits');
  if (process.env.SCREENSHOT) await page.screenshot({ path: process.env.SCREENSHOT });
  await page.reload();
  await pane('charlie').waitFor();
  a = await pane('alpha').boundingBox(); c = await pane('charlie').boundingBox();
  assert.ok(c.y > a.y && Math.abs(c.x - a.x) < 2, 'Arrangement and selected agents survive reload');
  await drag('charlie', 'bravo', 'left');
  c = await pane('charlie').boundingBox(); b = await pane('bravo').boundingBox();
  assert.ok(c.x < b.x && Math.abs(c.y - b.y) < 2, 'Dragging to a side creates a horizontal split');
  await page.getByLabel('Choose visible agents').click();
  await page.getByRole('checkbox', { name: 'bravo', exact: true }).uncheck();
  await pane('bravo').waitFor({ state: 'detached' });
  await page.getByLabel('Choose visible agents').click();
  assert.equal(await pane('alpha').count(), 1);
  assert.deepEqual(writes, [], 'Choosing, arranging and resizing panes never mutates an agent');
  await page.route('**/api/state', r => r.fulfill({ json: { mode: 'ask', agents, archived: [], messages: {}, tasks: [], taskNotes: [], inbox: [], paneLinks: { charlie: 'bravo' }, tags: {}, boards: [], sources: [], models: [], backends: [] } }));
  await page.goto(`${process.env.TEST_URL ?? 'http://localhost:3941'}/?agent=bravo`);
  await pane('charlie').waitFor();
  assert.equal(await pane('alpha').count(), 0, 'Custom arrangements stay scoped to their view');
  assert.equal(await page.evaluate(() => localStorage.getItem('oxroute.panes.bravo')), null, 'Automatic fork grouping is not converted into a custom view');
  await page.reload();
  await pane('charlie').waitFor();
  console.log('Pane selection, nested splits, resize, drafts and reload persistence pass.');
} finally { await browser.close(); }
