import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const agents = ['alpha', 'bravo', 'charlie'].map(id => ({ id, name: id, cwd: '/workspace', backend: 'codex', model: 'test', status: 'complete', updatedAt: Date.now()/1000 }));
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  const writes = [];
  page.on('request', request => { if (request.method() !== 'GET') writes.push(request.url()); });
  await page.route('**/api/state', r => r.fulfill({ json: { mode: 'ask', agents, archived: [], messages: {}, tasks: [], taskNotes: [], inbox: [], paneLinks: {}, tags: {}, boards: [], sources: [], models: [], backends: [] } }));
  await page.route('**/api/events', r => r.fulfill({ contentType: 'text/event-stream', body: ': test\n\n' }));
  await page.route('**/api/agents/*', r => {
    const agent = agents.find(agent => r.request().url().endsWith('/' + agent.id));
    return r.fulfill({ json: { agent, timeline: Array.from({ length: 60 }, (_, index) => ({ id: index + 1, agentId: agent.id, kind: 'said', detail: '', text: `Example message ${index + 1}\n\nA second paragraph for reading.`, at: Date.now()/1000 })), delivery: 'start' } });
  });
  await page.goto(`${process.env.TEST_URL ?? 'http://localhost:3941'}/?agent=alpha`);
  const pane = id => page.locator(`[data-agent-pane="${id}"]`);
  await pane('alpha').waitFor();
  await page.getByLabel('Choose visible agents').click();
  await page.getByLabel('Filter agents').fill('alpha');
  assert.equal(await page.getByLabel('Visible agents', { exact: true }).isVisible(), true, 'Inside clicks retain picker');
  await pane('alpha').locator('[data-transcript]').click();
  await page.getByLabel('Visible agents', { exact: true }).waitFor({ state: 'detached' });
  await page.getByLabel('Choose visible agents').click();
  await page.getByLabel('Filter agents').fill('');
  await page.keyboard.press('Escape');
  await page.getByLabel('Visible agents', { exact: true }).waitFor({ state: 'detached' });
  const picker = page.getByLabel('Choose visible agents');
  assert.equal(await picker.innerText(), '', 'Pane picker is icon-only');
  const pickerBox = await picker.boundingBox(), settingsBox = await page.getByRole('button', { name: 'Settings', exact: true }).boundingBox();
  assert.ok(Math.abs(pickerBox.x - settingsBox.x - settingsBox.width) < 2, 'Pane picker sits beside the left toolbar icons');
  assert.equal(pickerBox.width, settingsBox.width, 'Pane picker matches toolbar cell size');
  await pane('alpha').locator('[data-composer]').fill('Keep this draft.');
  await page.getByLabel('Choose visible agents').click();
  await page.getByRole('checkbox', { name: 'bravo', exact: true }).check();
  await page.getByRole('checkbox', { name: 'charlie', exact: true }).check();
  await page.getByLabel('Choose visible agents').click();
  await pane('charlie').waitFor();
  const edge = async id => pane(id).evaluate(el => getComputedStyle(el, '::after').boxShadow);
  await pane('alpha').locator('[data-transcript]').click();
  const focusedEdge = await edge('alpha'), quietEdge = await edge('bravo');
  assert.notEqual(focusedEdge, quietEdge, 'Focus changes edge shade');
  for (const shadow of [focusedEdge, quietEdge]) assert.ok(shadow.includes('0px 0px 0px 1px'), 'Focused and inactive edges retain the same single-pixel width');
  const drag = async (source, target, edge) => {
    const box = await pane(target).boundingBox();
    const handle = page.getByRole('button', { name: `Move pane ${source}`, exact: true });
    const x = edge === 'left' ? 10 : edge === 'right' ? box.width - 10 : box.width/2;
    const y = edge === 'top' ? 10 : edge === 'bottom' ? box.height - 10 : box.height/2;
    await handle.dragTo(pane(target), { targetPosition: { x, y } });
  };
  await drag('charlie', 'alpha', 'bottom');
  let a = await pane('alpha').boundingBox(), c = await pane('charlie').boundingBox(), b = await pane('bravo').boundingBox();
  assert.ok(c.y > a.y && Math.abs(c.x - a.x) < 2 && b.x > a.x, 'Nested vertical and horizontal panes share the view');
  assert.ok(Math.abs(c.y - a.y - a.height) < 0.5 && Math.abs(b.x - a.x - a.width) < 0.5, 'Panes meet without horizontal or vertical gaps');
  assert.equal(await pane('alpha').locator('[data-composer]').inputValue(), 'Keep this draft.', 'Moving panes retains message drafts');
  const verticalSplit = page.locator('[role="separator"][aria-orientation="horizontal"]');
  await verticalSplit.focus();
  const before = (await pane('alpha').boundingBox()).height;
  await verticalSplit.press('ArrowDown');
  assert.ok((await pane('alpha').boundingBox()).height > before, 'Split divider resizes vertically');
  assert.ok(await page.getByRole('separator', { name: 'resize chat panes' }).count() >= 2);
  const sideDivider = page.locator('[role="separator"][aria-orientation="vertical"]').first();
  const sideBox = await sideDivider.boundingBox(), oldWidth = (await pane('alpha').boundingBox()).width;
  await page.mouse.move(sideBox.x + sideBox.width/2, sideBox.y + sideBox.height/2);
  await page.mouse.down();
  await page.mouse.move(sideBox.x + 60, sideBox.y + sideBox.height/2, { steps: 6 });
  await page.mouse.up();
  assert.ok((await pane('alpha').boundingBox()).width > oldWidth, 'Pointer dragging resizes horizontal splits');
  const junction = page.getByRole('separator', { name: 'Resize pane intersection', exact: true }).first();
  assert.equal(await junction.evaluate(node => getComputedStyle(node).backgroundColor), 'rgba(0, 0, 0, 0)', 'Intersection drag target has no visible box');
  const junctionBox = await junction.boundingBox(), beforeCorner = await pane('alpha').boundingBox();
  await page.mouse.move(junctionBox.x + junctionBox.width/2, junctionBox.y + junctionBox.height/2);
  await page.mouse.down();
  await page.mouse.move(junctionBox.x + junctionBox.width/2 + 40, junctionBox.y + junctionBox.height/2 + 35, { steps: 6 });
  await page.mouse.up();
  const afterCorner = await pane('alpha').boundingBox();
  assert.ok(afterCorner.width > beforeCorner.width + 30 && afterCorner.height > beforeCorner.height + 25, 'Intersection dragging resizes both axes simultaneously');
  await page.evaluate(() => document.activeElement?.blur());
  await page.keyboard.press('j');
  assert.equal(await pane('charlie').getAttribute('data-pane-active'), 'true', 'j selects the pane below');
  await page.keyboard.press('k');
  assert.equal(await pane('alpha').getAttribute('data-pane-active'), 'true', 'k selects the pane above');
  await page.keyboard.press('l');
  assert.equal(await pane('bravo').getAttribute('data-pane-active'), 'true', 'l selects the pane to the right');
  await page.keyboard.press('i');
  assert.equal(await pane('bravo').getAttribute('data-pane-mode'), 'reading');
  await page.keyboard.press('g'); await page.keyboard.press('g');
  await page.waitForFunction(() => document.querySelector('[data-pane-active="true"] [data-transcript]').scrollTop === 0);
  const otherScroll = await pane('alpha').locator('[data-transcript]').evaluate(node => node.scrollTop);
  await page.keyboard.press('j');
  await page.waitForFunction(() => document.querySelector('[data-pane-active="true"] [data-transcript]').scrollTop > 0);
  assert.equal(await pane('alpha').locator('[data-transcript]').evaluate(node => node.scrollTop), otherScroll, 'Reading scrolls only the selected pane');
  await page.keyboard.press('G');
  await page.waitForFunction(() => { const node = document.querySelector('[data-pane-active="true"] [data-transcript]'); return node.scrollTop + node.clientHeight >= node.scrollHeight - 2; });
  await page.keyboard.press('Enter');
  assert.ok(await pane('bravo').locator('[data-composer]').evaluate(node => node === document.activeElement), 'Enter focuses the selected composer');
  await page.keyboard.type('Draft survives zoom.');
  await page.keyboard.press('Escape');
  await page.keyboard.press('z');
  assert.equal(await pane('alpha').isVisible(), false, 'Zoom hides other panes');
  assert.ok((await pane('bravo').boundingBox()).width > 1200, 'Zoom fills the pane workspace');
  await page.keyboard.press('z');
  assert.equal(await pane('alpha').isVisible(), true, 'Zoom restores the layout');
  assert.equal(await pane('bravo').locator('[data-composer]').inputValue(), 'Draft survives zoom.');
  await page.keyboard.press('Escape');
  await page.keyboard.press('h');
  assert.equal(await pane('alpha').getAttribute('data-pane-active'), 'true', 'h selects the pane to the left');
  if (process.env.SCREENSHOT) await page.screenshot({ path: process.env.SCREENSHOT });
  await page.reload();
  await pane('charlie').waitFor();
  a = await pane('alpha').boundingBox(); c = await pane('charlie').boundingBox();
  assert.ok(c.y > a.y && Math.abs(c.x - a.x) < 2, 'Arrangement and selected agents survive reload');
  assert.ok(Math.abs(a.width - afterCorner.width) < 2 && Math.abs(a.height - afterCorner.height) < 2, 'Both intersection dimensions survive reload');
  const dividerBox = await verticalSplit.boundingBox();
  await page.mouse.move(dividerBox.x + dividerBox.width/2, dividerBox.y);
  await page.mouse.down();
  await page.mouse.move(dividerBox.x + dividerBox.width/2, a.y + 1, { steps: 6 });
  await page.mouse.up();
  const header = await pane('alpha').locator('[data-pane-header]').boundingBox();
  assert.ok(Math.abs((await pane('alpha').boundingBox()).height - header.height) < 0.5, 'Pane can shrink to its titlebar');
  assert.ok(Math.abs((await pane('charlie').locator('[data-pane-header]').boundingBox()).y - header.y - header.height) < 0.5, 'Stacked titlebars meet without a gap');
  if (process.env.COLLAPSED_SCREENSHOT) await page.screenshot({ path: process.env.COLLAPSED_SCREENSHOT });
  await page.reload();
  await pane('charlie').waitFor();
  assert.ok(Math.abs((await pane('alpha').boundingBox()).height - header.height) < 0.5, 'Titlebar-sized pane survives reload');
  const collapsedDivider = await verticalSplit.boundingBox();
  await page.mouse.move(collapsedDivider.x + collapsedDivider.width/2, collapsedDivider.y);
  await page.mouse.down();
  await page.mouse.move(collapsedDivider.x + collapsedDivider.width/2, a.y + afterCorner.height, { steps: 6 });
  await page.mouse.up();
  await drag('charlie', 'bravo', 'left');
  c = await pane('charlie').boundingBox(); b = await pane('bravo').boundingBox();
  assert.ok(c.x < b.x && Math.abs(c.y - b.y) < 2, 'Dragging to a side creates a horizontal split');
  await page.getByLabel('Choose visible agents').click();
  await page.getByRole('checkbox', { name: 'bravo', exact: true }).uncheck();
  await pane('bravo').waitFor({ state: 'detached' });
  await page.getByLabel('Choose visible agents').click();
  assert.equal(await pane('alpha').count(), 1);
  await page.getByRole('button', { name: 'Move pane alpha', exact: true }).click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'Close pane', exact: true }).waitFor();
  if (process.env.MENU_SCREENSHOT) await page.screenshot({ path: process.env.MENU_SCREENSHOT });
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('menu', { name: 'Pane actions' }).count(), 0, 'Escape dismisses the pane menu');
  await page.getByRole('button', { name: 'Move pane alpha', exact: true }).click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'Close pane', exact: true }).click();
  await pane('alpha').waitFor({ state: 'detached' });
  assert.equal(await pane('charlie').count(), 1, 'Closing a pane preserves the other visible pane');
  await page.reload();
  await pane('charlie').waitFor();
  assert.equal(await pane('alpha').count(), 0, 'Closing the original pane persists across reloads');
  await page.getByRole('button', { name: 'Move pane charlie', exact: true }).click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'Close pane', exact: true }).click();
  await pane('charlie').waitFor({ state: 'detached' });
  assert.equal(new URL(page.url()).searchParams.get('agent'), null, 'Closing the final pane returns to the fleet');
  assert.deepEqual(writes, [], 'Choosing, arranging and resizing panes never mutates an agent');
  await page.route('**/api/state', r => r.fulfill({ json: { mode: 'ask', agents, archived: [], messages: {}, tasks: [], taskNotes: [], inbox: [], paneLinks: { charlie: 'bravo' }, tags: {}, boards: [], sources: [], models: [], backends: [] } }));
  await page.goto(`${process.env.TEST_URL ?? 'http://localhost:3941'}/?agent=bravo`);
  await pane('charlie').waitFor();
  assert.equal(await pane('alpha').count(), 0, 'Custom arrangements stay scoped to their view');
  assert.equal(await page.evaluate(() => localStorage.getItem('oxroute.panes.bravo')), null, 'Automatic fork grouping is not converted into a custom view');
  await page.reload();
  await pane('charlie').waitFor();
  console.log('Pane selection, nested splits, resize, drafts and reload persistence pass.');
} finally { await browser.close(); }
