import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const agents = ['alpha', 'bravo'].map(id => ({ id, name: id, cwd: '/workspace', backend: 'codex', model: 'test', status: 'complete', updatedAt: Date.now()/1000 }));
const tasks = [{ id: 'density-task', text: 'A readable task', status: 'incomplete', agentId: 'alpha', blockedByTaskId: '', images: [], createdAt: 1, updatedAt: 1, position: 0 }];
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  const writes = [];
  page.on('request', request => { if (request.method() !== 'GET') writes.push(request.url()); });
  await page.route('**/api/state', route => route.fulfill({ json: { mode: 'ask', agents, archived: [], tasks, taskNotes: [], messages: {}, inbox: [], paneLinks: {}, tags: {}, boards: [], sources: [], models: [], backends: [] } }));
  await page.route('**/api/events', route => route.fulfill({ contentType: 'text/event-stream', body: ': test\n\n' }));
  await page.route('**/api/agents/*', route => {
    const agent = agents.find(agent => route.request().url().endsWith('/' + agent.id));
    return route.fulfill({ json: { agent, timeline: [{ id: 1, agentId: agent.id, kind: 'said', text: 'Conversation stays available when the pane expands.', detail: '', at: 1 }], delivery: 'start' } });
  });
  const url = `${process.env.TEST_URL ?? 'http://127.0.0.1:3941'}/?agent=alpha`;
  await page.goto(url);
  const pane = id => page.locator(`[data-agent-pane="${id}"]`);
  await pane('alpha').locator('[data-composer]').fill('Preserve this draft.');
  await page.getByLabel('Choose visible agents').click();
  await page.getByRole('checkbox', { name: 'bravo', exact: true }).check();
  await page.getByLabel('Choose visible agents').click();
  await page.getByRole('button', { name: 'Show or hide tasks', exact: true }).click();
  const sidebar = page.getByRole('complementary', { name: 'Tasks', exact: true });
  const right = await pane('bravo').boundingBox(), taskBox = await sidebar.boundingBox();
  assert.ok(Math.abs(right.x + right.width - taskBox.x) < 0.5, 'Panes meet the task sidebar without a gap');
  const divider = page.getByRole('separator', { name: 'resize chat panes', exact: true });
  const drag = async x => {
    const box = await divider.boundingBox();
    await page.mouse.move(box.x, box.y + box.height/2);
    await page.mouse.down(); await page.mouse.move(x, box.y + box.height/2, { steps: 6 }); await page.mouse.up();
  };
  await drag(1);
  assert.ok((await pane('alpha').boundingBox()).width < 48, 'Pane shrinks to a dots-only rail');
  assert.ok(await pane('alpha').getByRole('button', { name: 'Move pane alpha', exact: true }).isVisible());
  assert.equal(await pane('alpha').locator('[data-pane-title]').isVisible(), false);
  assert.equal(await pane('alpha').locator('[data-composer]').isVisible(), false);
  if (process.env.SCREENSHOT) await page.screenshot({ path: process.env.SCREENSHOT });
  await drag(300);
  assert.ok(await pane('alpha').locator('[data-pane-title]').isVisible());
  assert.equal(await pane('alpha').locator('[data-composer]').inputValue(), 'Preserve this draft.');
  await drag(1);
  await page.reload(); await pane('bravo').waitFor();
  assert.ok((await pane('alpha').boundingBox()).width < 48, 'Rail width survives reload');
  await drag(300);
  assert.ok(await pane('alpha').locator('[data-pane-title]').isVisible());
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'settings' });
  const scaling = dialog.locator('section').filter({ has: page.getByText('Scale panes with width', { exact: true }) });
  await scaling.getByRole('button').nth(1).click();
  const percentage = dialog.getByRole('spinbutton', { name: 'Minimum pane scale' });
  await percentage.focus();
  await percentage.press('ControlOrMeta+A');
  await percentage.pressSequentially('85');
  if (process.env.SETTINGS_SCREENSHOT) await page.screenshot({ path: process.env.SETTINGS_SCREENSHOT });
  await page.keyboard.press('Escape');
  const zoom = locator => locator.evaluate(node => Number(getComputedStyle(node).zoom));
  assert.equal(await zoom(pane('alpha').locator('[data-agent-panel]')), 0.85);
  if (!await sidebar.isVisible()) await page.getByRole('button', { name: 'Show or hide tasks', exact: true }).click();
  assert.equal(await zoom(sidebar), 0.85, 'Task sidebar uses the same chosen minimum');
  const scaledBox = await sidebar.boundingBox(), wrapperBox = await page.locator('[data-task-pane]').boundingBox();
  assert.ok(Math.abs(scaledBox.width - wrapperBox.width) < 0.5 && Math.abs(scaledBox.height - wrapperBox.height) < 0.5, 'Scaled tasks fill their sidebar');
  await page.reload(); await pane('alpha').waitFor();
  assert.equal(await zoom(pane('alpha').locator('[data-agent-panel]')), 0.85, 'Custom scale persists');
  const taskDivider = page.getByRole('separator', { name: 'resize tasks', exact: true });
  const taskEdge = await taskDivider.boundingBox();
  await page.mouse.move(taskEdge.x, taskEdge.y + taskEdge.height / 2);
  await page.mouse.down();
  await page.mouse.move(1280 - 180, taskEdge.y + taskEdge.height / 2, { steps: 6 });
  await page.mouse.up();
  assert.equal((await page.locator('[data-task-pane]').boundingBox()).width, 180, 'Task sidebar can shrink below its old minimum');
  if (process.env.NARROW_SCREENSHOT) await page.screenshot({ path: process.env.NARROW_SCREENSHOT });
  await page.reload(); await pane('alpha').waitFor();
  assert.equal((await page.locator('[data-task-pane]').boundingBox()).width, 180, 'Narrow task width persists');
  await taskDivider.focus(); await taskDivider.press('ArrowRight');
  for (let i = 0; i < 10; i++) await taskDivider.press('ArrowRight');
  assert.equal((await page.locator('[data-task-pane]').boundingBox()).width, 34, 'Task sidebar collapses to a thin rail');
  assert.ok(await sidebar.locator('[data-task-rail]').isVisible());
  assert.equal(await sidebar.getByRole('searchbox', { name: 'Search tasks' }).isVisible(), false);
  if (process.env.RAIL_SCREENSHOT) await page.screenshot({ path: process.env.RAIL_SCREENSHOT });
  await page.reload(); await pane('alpha').waitFor();
  assert.equal((await page.locator('[data-task-pane]').boundingBox()).width, 34, 'Collapsed task width persists');
  const railEdge = await taskDivider.boundingBox();
  await page.mouse.move(railEdge.x, railEdge.y + railEdge.height / 2);
  await page.mouse.down(); await page.mouse.move(1280 - 180, railEdge.y + railEdge.height / 2, { steps: 6 }); await page.mouse.up();
  assert.ok(await sidebar.getByRole('searchbox', { name: 'Search tasks' }).isVisible());
  assert.ok(await sidebar.getByRole('combobox', { name: 'status for A readable task' }).isVisible());
  assert.deepEqual(writes, [], 'Layout and scale settings never mutate agent or task data');
  console.log('Dots-only rails, flush sidebar, draft restoration, custom scale and task scaling pass.');
} finally { await browser.close(); }
