import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const terminal = { id: 'terminal_display', name: 'Shared shell', pending: [], granted: [] };
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1100, height: 750 } });
  const writes = [], reads = [], errors = [];
  page.on('request', r => { if (r.method() !== 'GET') writes.push(r.url()); });
  page.on('pageerror', e => errors.push(String(e)));
  await page.route('**/api/state', r => r.fulfill({ json: { mode: 'ask', agents: [], archived: [], messages: {}, tasks: [], taskNotes: [], inbox: [], paneLinks: {}, tags: {}, boards: [], sources: [], models: [], backends: [] } }));
  await page.route('**/api/events', r => r.fulfill({ contentType: 'text/event-stream', body: ': test\n\n' }));
  await page.route('**/api/terminals', r => r.fulfill({ json: [terminal] }));
  const bytes = [...Buffer.from('Shell history survives theme changes.\r\n')];
  await page.route(`**/api/terminals/${terminal.id}?*`, async r => {
    reads.push(r.request().url());
    if (reads.length > 1) await new Promise(resolve => setTimeout(resolve, 2000));
    await r.fulfill({ json: { terminal, bytes: reads.length === 1 ? bytes : [], end: bytes.length, reset: false } }).catch(() => {});
  });
  await page.goto(`${process.env.TEST_URL ?? 'http://127.0.0.1:3941'}/?agent=${terminal.id}`);
  const pane = page.locator('[data-terminal-pane]');
  await pane.locator('.xterm-rows').getByText('Shell history survives theme changes.').waitFor();
  const foreground = () => pane.locator('.xterm-rows > div').first().evaluate(node => getComputedStyle(node).color);
  const setTheme = async index => {
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    const dialog = page.getByRole('dialog', { name: 'settings' });
    await dialog.locator('section').filter({ has: page.getByText('Look', { exact: true }) }).getByRole('button').nth(index).click();
    await page.keyboard.press('Escape');
    await page.waitForTimeout(100);
  };
  await setTheme(0);
  const light = await foreground();
  if (process.env.SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.SCREENSHOT_DIR}/terminal-light.png` });
  await setTheme(1);
  assert.notEqual(await foreground(), light, 'Terminal palette follows the app theme');
  assert.ok((await pane.locator('.xterm-rows').innerText()).includes('Shell history survives theme changes.'));
  if (process.env.SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.SCREENSHOT_DIR}/terminal-dark.png` });
  const text = pane.locator('.xterm-rows > div > span').first();
  const originalText = await text.boundingBox();
  const originalHeader = await pane.locator('[data-pane-header]').boundingBox();
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'settings' });
  await dialog.locator('section').filter({ has: page.getByText('Scale panes with width', { exact: true }) }).getByRole('button').nth(1).click();
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 500, height: 750 });
  await page.waitForTimeout(100);
  assert.equal(await pane.evaluate(node => Number(getComputedStyle(node).zoom)), 0.7, 'Terminal uses the shared scale floor');
  assert.ok(Math.abs((await text.boundingBox()).height - originalText.height * 0.7) <= 1, 'Terminal text scales with its pane');
  assert.ok(Math.abs((await pane.locator('[data-pane-header]').boundingBox()).height - originalHeader.height * 0.7) < 0.5, 'Terminal titlebar scales with its pane');
  const screen = await pane.locator('.xterm-screen').boundingBox(), host = await pane.getByLabel('Interactive terminal').boundingBox();
  assert.ok(screen.width <= host.width && screen.height <= host.height, 'Terminal cells still fit the scaled viewport');
  const cell = await text.boundingBox(), cellWidth = cell.width / (await text.textContent()).length;
  await page.mouse.move(cell.x + 0.1, cell.y + cell.height / 2);
  await page.mouse.down(); await page.mouse.move(cell.x + cellWidth * 5 + 0.1, cell.y + cell.height / 2); await page.mouse.up();
  const copied = await pane.locator('.xterm').evaluate(node => {
    const data = new DataTransfer();
    node.dispatchEvent(new ClipboardEvent('copy', { clipboardData: data, bubbles: true }));
    return data.getData('text/plain');
  });
  assert.equal(copied, 'Shell', 'Mouse selection still matches visible cells when scaled');
  if (process.env.SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.SCREENSHOT_DIR}/terminal-scaled.png` });
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await dialog.getByRole('spinbutton', { name: 'Minimum pane scale' }).fill('85');
  await page.keyboard.press('Escape');
  assert.equal(await pane.evaluate(node => Number(getComputedStyle(node).zoom)), 0.85, 'Terminal follows the chosen scale floor');
  await page.setViewportSize({ width: 1100, height: 750 });
  await page.waitForTimeout(100);
  assert.equal(await pane.evaluate(node => Number(getComputedStyle(node).zoom)), 1, 'Terminal returns to full size when widened');
  assert.ok(reads.length >= 2 && reads.every(url => url.includes('wait=true')), 'Output uses waiting reads');
  assert.ok(reads[1].includes(`after=${bytes.length}`), 'Only new output is requested');
  assert.deepEqual(writes, [], 'Display verification never mutates terminal sessions');
  assert.deepEqual(errors, []);
  console.log('Terminal waiting reads and light/dark switching preserve shell history without mutations.');
} finally { await browser.close(); }
